sudo: required
services:
  - docker

before_install:
  - docker build -t arsh7023/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true arsh7023/react-test npm run test -- --coverage

after_success:
  - docker build -t  arsh7023/multi-client ./client
  - docker build -t  arsh7023/multi-nginx ./nginx
  - docker build -t  arsh7023/multi-server ./server
  - docker build -t  arsh7023/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push arsh7023/multi-client
  - docker push arsh7023/multi-nginx
  - docker push arsh7023/multi-server
  - docker push arsh7023/multi-worker

